In [1]:
#import libraries to be used in project
import snscrape.modules.twitter as sntwitter
import pandas as pd

In [2]:
#set search parameters for snscrape
query = "i for lef ghana until:2022-11-19 since:2021-01-01"
limit = 5000

#initialize list to which tweets will be appended
tweets = []

In [7]:
#instruct snscrape to pull tweets based on earlier parameters and append to earlier list
for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.user.username, tweet.content,tweet.sourceLabel])

In [8]:
#append tweets in list to dataframe using pandas
df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet', 'Tweet Source'])
df

,Date,User,Tweet,Tweet Source
0,2022-11-18 11:35:07+00:00,_kimss__,I for lef Ghana,None
1,2022-11-17 10:07:23+00:00,yed__ahh,"This is where the ""I for lef Ghana"" comes in. ...",None
2,2022-11-16 08:15:21+00:00,skukzxz,@kobe_flacko Brooo I spoil there . Your man sa...,None
3,2022-11-15 15:29:26+00:00,qwaci_rain,@gyaigyimii ‚ÄúI for lef Ghana‚Äù,None
4,2022-11-15 13:22:53+00:00,AndyPoundyJnr,Got my Passport in 2 days after Protocol payme...,None
...,...,...,...,...
4995,2022-08-18 08:20:35+00:00,KwameAsiedu_,I for lef Ghana IJN üôè,Twitter for Android
4996,2022-08-17 16:10:05+00:00,Amegaxi,"If ""I for lef Ghana"" was a person https://t.co...",Twitter for Android
4997,2022-08-17 15:06:20+00:00,theLassie_,I for lef Ghana,Twitter for iPhone
4998,2022-08-17 14:58:40+00:00,Papa_Of0ri,Man for lef Ghana. I can‚Äôt again with these ba...,Twitter for iPhone
4999,2022-08-16 18:28:32+00:00,rashbaey,I go go lef dem for Bortianor plus Ghana must ...,Twitter for iPhone

In [9]:
df.to_csv('tweets2022_11_19.csv')

In [10]:
#initialize target string to discard: "@i_for_lef_ghana"
discard = ["@i_for_lef_ghana"]

In [2]:
#discarding rows containing the target string then displaying results

#df[tweet.str.contains('|'.join(discard))]

for row in df:
    if

df = pd.read_csv('tweets2022_11_19.csv')
df

,Unnamed: 0,Date,User,Tweet,Tweet Source
0,0,2022-11-18 11:35:07+00:00,_kimss__,I for lef Ghana,NaN
1,1,2022-11-17 10:07:23+00:00,yed__ahh,"This is where the ""I for lef Ghana"" comes in. ...",NaN
2,2,2022-11-16 08:15:21+00:00,skukzxz,@kobe_flacko Brooo I spoil there . Your man sa...,NaN
3,3,2022-11-15 15:29:26+00:00,qwaci_rain,@gyaigyimii ‚ÄúI for lef Ghana‚Äù,NaN
4,4,2022-11-15 13:22:53+00:00,AndyPoundyJnr,Got my Passport in 2 days after Protocol payme...,NaN
...,...,...,...,...,...
4995,4995,2022-08-18 08:20:35+00:00,KwameAsiedu_,I for lef Ghana IJN üôè,Twitter for Android
4996,4996,2022-08-17 16:10:05+00:00,Amegaxi,"If ""I for lef Ghana"" was a person https://t.co...",Twitter for Android
4997,4997,2022-08-17 15:06:20+00:00,theLassie_,I for lef Ghana,Twitter for iPhone
4998,4998,2022-08-17 14:58:40+00:00,Papa_Of0ri,Man for lef Ghana. I can‚Äôt again with these ba...,Twitter for iPhone
4999,4999,2022-08-16 18:28:32+00:00,rashbaey,I go go lef dem for Bortianor plus Ghana must ...,Twitter for iPhone

In [4]:
#df[~df.Tweet.str.contains("@i_for_lef_ghana")]

df[~df.Tweet.str.contains('|'.join("@i_for_lef_ghana"))]
df

,Unnamed: 0,Date,User,Tweet,Tweet Source
0,0,2022-11-18 11:35:07+00:00,_kimss__,I for lef Ghana,NaN
1,1,2022-11-17 10:07:23+00:00,yed__ahh,"This is where the ""I for lef Ghana"" comes in. ...",NaN
2,2,2022-11-16 08:15:21+00:00,skukzxz,@kobe_flacko Brooo I spoil there . Your man sa...,NaN
3,3,2022-11-15 15:29:26+00:00,qwaci_rain,@gyaigyimii ‚ÄúI for lef Ghana‚Äù,NaN
4,4,2022-11-15 13:22:53+00:00,AndyPoundyJnr,Got my Passport in 2 days after Protocol payme...,NaN
...,...,...,...,...,...
4995,4995,2022-08-18 08:20:35+00:00,KwameAsiedu_,I for lef Ghana IJN üôè,Twitter for Android
4996,4996,2022-08-17 16:10:05+00:00,Amegaxi,"If ""I for lef Ghana"" was a person https://t.co...",Twitter for Android
4997,4997,2022-08-17 15:06:20+00:00,theLassie_,I for lef Ghana,Twitter for iPhone
4998,4998,2022-08-17 14:58:40+00:00,Papa_Of0ri,Man for lef Ghana. I can‚Äôt again with these ba...,Twitter for iPhone
4999,4999,2022-08-16 18:28:32+00:00,rashbaey,I go go lef dem for Bortianor plus Ghana must ...,Twitter for iPhone

In [5]:
type(df[Tweet])

NameError: name 'Tweet' is not defined

In [10]:
df[Tweet].dtype

NameError: name 'Tweet' is not defined